[2023-10-22T09:42:15.325+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.fetch_data_from_psql manual__2023-10-22T09:42:12.202398+00:00 [queued]>
[2023-10-22T09:42:15.343+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.fetch_data_from_psql manual__2023-10-22T09:42:12.202398+00:00 [queued]>
[2023-10-22T09:42:15.344+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T09:42:15.366+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_data_from_psql> on 2023-10-22 09:42:12.202398+00:00
[2023-10-22T09:42:15.379+0000] {standard_task_runner.py:57} INFO - Started process 1788 to run task
[2023-10-22T09:42:15.384+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'fetch_data_from_psql', 'manual__2023-10-22T09:42:12.202398+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmp_twbb4fb']
[2023-10-22T09:42:15.390+0000] {standard_task_runner.py:85} INFO - Job 245: Subtask fetch_data_from_psql
[2023-10-22T09:42:15.483+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.fetch_data_from_psql manual__2023-10-22T09:42:12.202398+00:00 [running]> on host 90cf752d844d
[2023-10-22T09:42:16.266+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='fetch_data_from_psql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T09:42:12.202398+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T09:42:12.202398+00:00'
[2023-10-22T09:42:16.291+0000] {base.py:73} INFO - Using connection ID 'postgresql_db' for task execution.
[2023-10-22T09:42:18.352+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-10-22T09:42:18.664+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-22T09:42:18.676+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_day18, task_id=fetch_data_from_psql, execution_date=20231022T094212, start_date=20231022T094215, end_date=20231022T094218
[2023-10-22T09:42:18.717+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T09:42:18.746+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
